const cookies = [
    {
        domain: ".youtube.com",
        expirationDate: 1787163149.268276,
        hostOnly: false,
        httpOnly: true,
        name: "__Secure-3PSID",
        path: "/",
        sameSite: "no_restriction",
        secure: true,
        session: false,
        value: "g.a000zAjO2L2D-fxc2h0jxiC2634hxIGK9__vkIBTPIULNzLmHgyybKu-P9N3XoGJ56Q5VUjQdgACgYKAUUSARcSFQHGX2MiqL9al18ojPxDubirc8QUUBoVAUF8yKrQvghNsMn_pVJKEqM909SZ0076"
    },
    {
        domain: ".youtube.com",
        expirationDate: 1752603661.874727,
        hostOnly: false,
        httpOnly: true,
        name: "GPS",
        path: "/",
        sameSite: null,
        secure: true,
        session: false,
        value: "1"
    },
    {
        domain: ".youtube.com",
        expirationDate: 1784139171.731898,
        hostOnly: false,
        httpOnly: false,
        name: "SIDCC",
        path: "/",
        sameSite: null,
        secure: false,
        session: false,
        value: "AKEyXzW6EVvu37Cgj1v7aQsw7uiEBz4c_axJzdjyDjFUkrbUZkzO29yoVn0Cs8kNUNf7kXml-w"
    },
    {
        domain: ".youtube.com",
        expirationDate: 1787163149.268204,
        hostOnly: false,
        httpOnly: false,
        name: "SID",
        path: "/",
        sameSite: null,
        secure: false,
        session: false,
        value: "g.a000zAjO2L2D-fxc2h0jxiC2634hxIGK9__vkIBTPIULNzLmHgyy3OjjTe46RMO2PY3J5kc3gAACgYKAZ4SARcSFQHGX2MioIUvjbDk5vKnQ-SC6YYvmhoVAUF8yKoazLCuJ6oAF71kKgBPz2qG0076"
    },
    {
        domain: ".youtube.com",
        expirationDate: 1784139125.039888,
        hostOnly: false,
        httpOnly: true,
        name: "__Secure-1PSIDTS",
        path: "/",
        sameSite: null,
        secure: true,
        session: false,
        value: "sidts-CjIB5H03PzWC5Lsve8J3jWEHghigJJ3zTJJlESwyrnlPOpdPndJTFXn8d-Ckhi7Z6LogdxAA"
    },
    {
        domain: ".youtube.com",
        expirationDate: 1787163149.267993,
        hostOnly: false,
        httpOnly: false,
        name: "SAPISID",
        path: "/",
        sameSite: null,
        secure: true,
        session: false,
        value: "Zd_vczFbNzk7nfOj/A31uBcyOPA1iRjMMF"
    },
    {
        domain: ".youtube.com",
        expirationDate: 1784139171.732119,
        hostOnly: false,
        httpOnly: true,
        name: "__Secure-1PSIDCC",
        path: "/",
        sameSite: null,
        secure: true,
        session: false,
        value: "AKEyXzWLgyyJtlwIX4VIX3Otm-HMjwoMMzJfCtbB-WE-E0O0R77HNSzgUCEJ-WCemKRZnx0p"
    },
    {
        domain: ".youtube.com",
        expirationDate: 1787163149.267909,
        hostOnly: false,
        httpOnly: true,
        name: "SSID",
        path: "/",
        sameSite: null,
        secure: true,
        session: false,
        value: "AhI_WQ2ybctjIOr2Z"
    },
    {
        domain: ".youtube.com",
        expirationDate: 1787163149.268029,
        hostOnly: false,
        httpOnly: false,
        name: "__Secure-1PAPISID",
        path: "/",
        sameSite: null,
        secure: true,
        session: false,
        value: "Zd_vczFbNzk7nfOj/A31uBcyOPA1iRjMMF"
    },
    {
        domain: ".youtube.com",
        expirationDate: 1787163149.26824,
        hostOnly: false,
        httpOnly: true,
        name: "__Secure-1PSID",
        path: "/",
        sameSite: null,
        secure: true,
        session: false,
        value: "g.a000zAjO2L2D-fxc2h0jxiC2634hxIGK9__vkIBTPIULNzLmHgyy_P0MlbhWRUDS3pxGrt33SgACgYKAawSARcSFQHGX2MiLAYctJYF9gf_4dwIPue_fRoVAUF8yKrrSqc_xRKCyODuD6fbNuYn0076"
    },
    {
        domain: ".youtube.com",
        expirationDate: 1787163149.268064,
        hostOnly: false,
        httpOnly: false,
        name: "__Secure-3PAPISID",
        path: "/",
        sameSite: "no_restriction",
        secure: true,
        session: false,
        value: "Zd_vczFbNzk7nfOj/A31uBcyOPA1iRjMMF"
    },
    {
        domain: ".youtube.com",
        expirationDate: 1784139171.732227,
        hostOnly: false,
        httpOnly: true,
        name: "__Secure-3PSIDCC",
        path: "/",
        sameSite: "no_restriction",
        secure: true,
        session: false,
        value: "AKEyXzWeXX9a4VPxSdlI233du6MutRIj3Wy5fcDAJAYFnV6hKDRmnntg4vJruTZmuxi-KuQO"
    },
    {
        domain: ".youtube.com",
        expirationDate: 1784139125.040345,
        hostOnly: false,
        httpOnly: true,
        name: "__Secure-3PSIDTS",
        path: "/",
        sameSite: "no_restriction",
        secure: true,
        session: false,
        value: "sidts-CjIB5H03PzWC5Lsve8J3jWEHghigJJ3zTJJlESwyrnlPOpdPndJTFXn8d-Ckhi7Z6LogdxAA"
    },
    {
        domain: ".youtube.com",
        expirationDate: 1787163149.267953,
        hostOnly: false,
        httpOnly: false,
        name: "APISID",
        path: "/",
        sameSite: null,
        secure: false,
        session: false,
        value: "_6MmFLWvaBiOoN3g/A4e5BE-cJ5VKSiHDT"
    },
    {
        domain: ".youtube.com",
        expirationDate: 1787163149.267811,
        hostOnly: false,
        httpOnly: true,
        name: "HSID",
        path: "/",
        sameSite: null,
        secure: false,
        session: false,
        value: "ALokCbQwPL3EOqa0q"
    },
    {
        domain: ".youtube.com",
        expirationDate: 1787162265.846912,
        hostOnly: false,
        httpOnly: true,
        name: "LOGIN_INFO",
        path: "/",
        sameSite: "no_restriction",
        secure: true,
        session: false,
        value: "AFmmF2swRgIhAKIAp781cQbuN6JDJqPLrT9H0SWAp-cWP5O0RED6UxW_AiEA3X9BSJmkxvk2DT_i6ndbPvEhKx9PBJpUpMqzfRA8BJM:QUQ3MjNmenkzWGxiTU5FaEtMNkJyTVpYc19RMjJ1WU5LYlByaHNpQmxlYm8zUFlKLUdHYWxxSkNqZ2dUcFVzeDBUckxBZHRFblFkSXprY2JpMl9UbnFveW1hclE4Vi1fS21FUGhRbXBCaXJFRENySElka3VMWjI0akxIWlZwSFRPcjVwZHl1SU5QRXBwQUJRT1JJVWpyd0J2Qmc0RC1XVDdB"
    },
    {
        domain: ".youtube.com",
        expirationDate: 1787163158.41125,
        hostOnly: false,
        httpOnly: false,
        name: "PREF",
        path: "/",
        sameSite: null,
        secure: true,
        session: false,
        value: "tz=America.Bogota"
    }
];

module.exports = cookies;
