const cookies = [
    {
        domain: ".youtube.com",
        expirationDate: 1773908639.929311,
        hostOnly: false,
        httpOnly: true,
        name: "VISITOR_PRIVACY_METADATA",
        path: "/",
        sameSite: "no_restriction",
        secure: true,
        session: false,
        value: "CgJQRRIEGgAgKg%3D%3D"
    },
    {
        domain: ".youtube.com",
        expirationDate: 1757919635.056966,
        hostOnly: false,
        httpOnly: true,
        name: "__Secure-3PSID",
        path: "/",
        sameSite: "no_restriction",
        secure: true,
        session: true,
        value: "g.a000uwhlVJ4I4AL-_sXL4n2vWfJ5efnfaTgG3MXWeKGPbHbymRsJkWNVyBAw9_yrLWQdu18-MwACgYKAVUSARMSFQHGX2MiRF_43q32BaRl3QZZOUc-WhoVAUF8yKpR5FDHp_JmYIhldB-fQ5XQ0076"
    },
    {
        domain: ".youtube.com",
        expirationDate: 1742372935.057186,
        hostOnly: false,
        httpOnly: true,
        name: "GPS",
        path: "/",
        sameSite: null,
        secure: true,
        session: false,
        value: "1"
    },
    {
        domain: ".youtube.com",
        expirationDate: 1773908639.92941,
        hostOnly: false,
        httpOnly: false,
        name: "SIDCC",
        path: "/",
        sameSite: null,
        secure: false,
        session: false,
        value: "AKEyXzXjuY8fJlU4ySHpoDIdZIIKdFGr9UMc5a8gjn342A-uqLPdhkhibQ5BGG-43X5aTczh"
    },
    {
        domain: ".youtube.com",
        expirationDate: 1774857308.145557,
        hostOnly: false,
        httpOnly: false,
        name: "SID",
        path: "/",
        sameSite: null,
        secure: false,
        session: true,
        value: "g.a000uwhlVJ4I4AL-_sXL4n2vWfJ5efnfaTgG3MXWeKGPbHbymRsJonAOKlQefJfB2heMtLYHeQACgYKAZASARMSFQHGX2Mi4uPjbFQi6MttiV1DF8F6fRoVAUF8yKpbHOQvB9Bh_xjEoNL6b1SR0076"
    },
    {
        domain: ".youtube.com",
        expirationDate: 1771833308.145351,
        hostOnly: false,
        httpOnly: true,
        name: "__Secure-1PSIDTS",
        path: "/",
        sameSite: null,
        secure: true,
        session: false,
        value: "sidts-CjEBEJ3XV1-Jb0nV-tm18YE7NjlQYaS2OD8WWtO_WaBmqOXXTzlfKNDo8sT-jS9osMYjEAA"
    },
    {
        domain: ".youtube.com",
        expirationDate: 1774857308.145517,
        hostOnly: false,
        httpOnly: false,
        name: "SAPISID",
        path: "/",
        sameSite: null,
        secure: true,
        session: true,
        value: "6Tq04_aIK7XTSHR9/AHWcGzrP35qDPVzlR"
    },
    {
        domain: ".youtube.com",
        expirationDate: 1773908639.92941,
        hostOnly: false,
        httpOnly: true,
        name: "__Secure-1PSIDCC",
        path: "/",
        sameSite: null,
        secure: true,
        session: false,
        value: "AKEyXzXYYk3UYkj00KMngdcC-a-lza3fb7ydyhR3KVjI-WdfUKeSHA5qvfYNlcxZoyL083KzCQ"
    },
    {
        domain: ".youtube.com",
        expirationDate: 1774857308.145494,
        hostOnly: false,
        httpOnly: true,
        name: "SSID",
        path: "/",
        sameSite: null,
        secure: true,
        session: true,
        value: "A0H_uCLtiF94rteUQ"
    },
    {
        domain: ".youtube.com",
        expirationDate: 1774857308.145529,
        hostOnly: false,
        httpOnly: false,
        name: "__Secure-1PAPISID",
        path: "/",
        sameSite: null,
        secure: true,
        session: true,
        value: "6Tq04_aIK7XTSHR9/AHWcGzrP35qDPVzlR"
    },
    {
        domain: ".youtube.com",
        expirationDate: 1774857308.145571,
        hostOnly: false,
        httpOnly: true,
        name: "__Secure-1PSID",
        path: "/",
        sameSite: null,
        secure: true,
        session: true,
        value: "g.a000tQhlMMXw6pxDnSh0QSzmyDL5nVAHq3oJby1HvoPvjONstWVZfvsmpjZwEbi_AC1OmLJtewACgYKASISARcSFQHGX2MirUSBBlxB5opMWPlHvC5wKRoVAUF8yKpcK6-YHxYSL-cW1BXfz7130076"
    },
    {
        domain: ".youtube.com",
        expirationDate: 1774857308.145541,
        hostOnly: false,
        httpOnly: false,
        name: "__Secure-3PAPISID",
        path: "/",
        sameSite: "no_restriction",
        secure: true,
        session: true,
        value: "6Tq04_aIK7XTSHR9/AHWcGzrP35qDPVzlR"
    },
    {
        domain: ".youtube.com",
        expirationDate: 1773908639.929454,
        hostOnly: false,
        httpOnly: true,
        name: "__Secure-3PSIDCC",
        path: "/",
        sameSite: "no_restriction",
        secure: true,
        session: false,
        value: "AKEyXzXg3ygpyKXj766rdmx3SLJ7Tn7e-LNabuW8N1uBT4_aWsJkKtB6ScTC2AAQJILXq_KK"
    },
    {
        domain: ".youtube.com",
        expirationDate: 1773908048.05971,
        hostOnly: false,
        httpOnly: true,
        name: "__Secure-3PSIDTS",
        path: "/",
        sameSite: "no_restriction",
        secure: true,
        session: false,
        value: "sidts-CjIB7pHptZ1MEkVYrhsK2xzhkZJk1NRfdgs-0wEFaE8IQk4xZCY9E1uA4jFm1FsaYnadvBAA"
    },
    {
        domain: ".youtube.com",
        expirationDate: 1774857308.145505,
        hostOnly: false,
        httpOnly: false,
        name: "APISID",
        path: "/",
        sameSite: null,
        secure: false,
        session: true,
        value: "r1XslNv_e6yzawhe/AZMIBZYtbItKHDvXZ"
    },
    {
        domain: ".youtube.com",
        hostOnly: false,
        httpOnly: true,
        name: "HSID",
        path: "/",
        sameSite: null,
        secure: false,
        session: true,
        value: "AP2iyVTzgjpXJI0Kf"
    },
    {
        domain: ".youtube.com",
        expirationDate: 1776931237.194519,
        hostOnly: false,
        httpOnly: true,
        name: "LOGIN_INFO",
        path: "/",
        sameSite: "no_restriction",
        secure: true,
        session: false,
        value: "AFmmF2swRAIgQhos1bNnQz8lYpjquANlhgGtHeA0qcrSz0Hjtp-fqVYCID6WFTAD-2aX9asuphKrOuZi90Ku265zF3qpsoQZ0B1D:QUQ3MjNmeXBoSGxhOHl6VUU0QjI4SmZOcEcwZm9xREdxV1puZkJSaFQ2SnZnekFQckVETndnSHZZV2lDcnhZT0ZVSU1tbERzcnA3ZlJ0Z3lqaFRMZVhZZGJKSno3RVkwenZhQ0pnTVFnOGN6RS1BeWt1WFNCY3owOTE2UDlLc0h6MmtfbFg2NlZvZGJKUnQ3d19ONVEyVW5BRldBOXZRaEhR"
    },
    {
        domain: ".youtube.com",
        expirationDate: 1776932637.576999,
        hostOnly: false,
        httpOnly: false,
        name: "PREF",
        path: "/",
        sameSite: null,
        secure: true,
        session: false,
        value: "f4=4000000&f6=40000000&tz=America.Lima&f7=100"
    },
    {
        domain: ".youtube.com",
        expirationDate: 1757919635.056857,
        hostOnly: false,
        httpOnly: true,
        name: "VISITOR_INFO1_LIVE",
        path: "/",
        sameSite: "no_restriction",
        secure: true,
        session: false,
        value: "_Sd71V5aYbs"
    }
];

module.exports = cookies;
